### ISSUE TITLE
Providing invalid zip code after providing valid zip code previously

### ISSUE THREAD

**Issue by sangv** [CJFreelancing/ZipCodes-By-Radius-App#1]
Providing invalid zip code after providing valid zip code previously shows i) No error messages and ii) shows previous results.

Steps to replicate:
i) Enter a valid zip code. I provided 30305
ii) Enter an invalid zipcode. I provided 16216 from https://gist.githubusercontent.com/dryan/7486408/raw/dda158f44480f8c433dc8fd1db9c07ed9aadf989/invalid-zips.json
iii) It shows the previous results. I would have expected it to clear out old results and preferably show an error/warning message.

**Comment by CJFreelancing** [comment]
I pushed some code to fix this issue. It now shows an error dialog and clears data when an invalid zipcode is entered. Thanks!
